mongosh

use movieDB

db.movies.insertMany([
  { title: "The Shawshank Redemption" },
  { title: "The Godfather" },
  { title: "The Dark Knight" },
  { title: "Pulp Fiction" },
  { title: "Forrest Gump" },
  { title: "Inception" },
  { title: "Fight Club" },
  { title: "The Matrix" },
  { title: "Goodfellas" },
  { title: "The Lord of the Rings: The Return of the King" },
  { title: "Star Wars: Episode V - The Empire Strikes Back" },
  { title: "The Silence of the Lambs" },
  { title: "Se7en" },
  { title: "Saving Private Ryan" },
  { title: "Interstellar" },
  { title: "The Green Mile" },
  { title: "Gladiator" },
  { title: "The Lion King" },
  { title: "Back to the Future" },
  { title: "Schindler's List" },
  { title: "Braveheart" },
  { title: "The Departed" },
  { title: "Whiplash" },
  { title: "The Prestige" },
  { title: "The Intouchables" },
  { title: "Parasite" },
  { title: "Joker" },
  { title: "Avengers: Endgame" },
  { title: "The Wolf of Wall Street" },
  { title: "The Social Network" },
  { title: "La La Land" },
  { title: "Django Unchained" },
  { title: "Inglourious Basterds" },
  { title: "The Grand Budapest Hotel" },
  { title: "Her" },
  { title: "Ex Machina" },
  { title: "The Truman Show" },
  { title: "The Big Lebowski" },
  { title: "No Country for Old Men" },
  { title: "There Will Be Blood" },
  { title: "The Revenant" },
  { title: "Birdman" },
  { title: "A Beautiful Mind" },
  { title: "Cast Away" },
  { title: "The Pianist" },
  { title: "Amélie" },
  { title: "Life of Pi" },
  { title: "Gravity" },
  { title: "12 Years a Slave" },
  { title: "Spotlight" },
  { title: "Arrival" },
  { title: "Blade Runner 2049" },
  { title: "The Imitation Game" }
])
